### ISSUE TITLE
Support floats

### ISSUE THREAD

**Issue by ashpil** [Absolucy/nanorand-rs#20]
It would be nice if it was possible to use nanorand to generate floats.

I know nothing about random number generation - would this be hard to implement?

**Comment by aspenluxxxy** [comment]
Probably not, I just don't know how.

**Comment by Absolucy** [comment]
Fixed in https://github.com/Absolucy/nanorand-rs/commit/47ac7bc3be66e1e7f8039bdbf62670ec6bbed61b: `f32` and `f64` now have a `RandomGen` implementation that will generate a random number in the range of  `0 <= x <= 1`
