### ISSUE TITLE
Mojibake in readme

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [Absolucy/nanorand-rs#34]
3b0042a905770c2b591242565f61a732a57b6974 corrupted the emoji in the readme: https://github.com/Absolucy/nanorand-rs/commit/3b0042a905770c2b591242565f61a732a57b6974#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R62-R64

**Comment by Absolucy** [comment]
Thanks for pointing this out!
