### ISSUE TITLE
error[E0425]: cannot find function `backup_entropy` in this scope

### ISSUE THREAD

**Issue by staystealth** [Absolucy/nanorand-rs#41]
Hi, one of my dependencies (wasmium-random) is using nanorand crate v0.6.1, my cargo throws an error while trying to build it, is there a way to change the v of nanorand inside of the other dep, also does the nanorand v0.7.0 solves this problem or are there any other solutions you could provide?

`error: could not compile "nanorand" due to previous error`

**Comment by Absolucy** [comment]
Try using the `getrandom` feature with nanorand?

**Comment by staystealth** [comment]
it works! thank you for your help
