### ISSUE TITLE
Generating signed integers within a range yields biased/incorrect values

### ISSUE THREAD

**Issue by TheV360** [Absolucy/nanorand-rs#9]
Generating an `isize` in the range [0, 192) produces values in the range [0, 96) heavily biased towards 0. Meanwhile, generating an `i32` generates values outside the requested range.

Since unsigned integers are unaffected by this, a way around the issue for now is generating unsigned integers from 0 to `max - min`, casting the result to a signed integer, and then adding `min` back in.
```rust
// As an example, I'm using WyRand
fn generate_signed_range(rng: &mut WyRand, min: isize, max: isize) -> isize {
	rng.generate_range::<usize>(0, (max - min) as usize) as isize + min
}
```

I saw that this is being addressed in another branch, but I wanted to make this issue more visible for other users of this library.

**Comment by aspenluxxxy** [comment]
I think this is due to my rather hacky implementation of Lemire's debiased method.

**Comment by Absolucy** [comment]
fixed in https://github.com/Absolucy/nanorand-rs/commit/8307f122a6ef66f9f7a4d6e749f81d8ce4a9691b, https://github.com/Absolucy/nanorand-rs/commit/7f992911535bb415859ab89406c0092ce393a64b
